#!/bin/bash
SCRIPTS=$PWD
rm ../symbolia-dark/scalable -r
rm ../symbolia-dark/symbolic -r
cp ../symbolia/scalable ../symbolia-dark/scalable -r
cp ../symbolia/symbolic ../symbolia-dark/symbolic -r
cd ../symbolia-dark/scalable/actions && $SCRIPTS/recolor-dark
cd ../apps && $SCRIPTS/recolor-dark
cd ../categories && $SCRIPTS/recolor-dark
cd ../devices && $SCRIPTS/recolor-dark
cd ../emblems && $SCRIPTS/recolor-dark
cd ../mimetypes && $SCRIPTS/recolor-dark
cd ../places && $SCRIPTS/recolor-dark
cd ../status && $SCRIPTS/recolor-dark
cd ../../symbolic/actions && $SCRIPTS/recolor-dark
cd ../apps && $SCRIPTS/recolor-dark
cd ../categories && $SCRIPTS/recolor-dark
cd ../devices && $SCRIPTS/recolor-dark
cd ../emblems && $SCRIPTS/recolor-dark
cd ../mimetypes && $SCRIPTS/recolor-dark
cd ../places && $SCRIPTS/recolor-dark
cd ../status && $SCRIPTS/recolor-dark
