#!/bin/bash
echo "Generating symbolic and scalable themes."
./icon-propogate
echo "Creating dark themes."
./create-dark-theme
echo "Creating neutral themes."
./create-neutral-theme
echo "Creating arc/nord themes."
./create-arc-theme
echo "Creating yaru themes."
./create-yaru-theme
echo "Coloring folder colors."
rm ../symbolia-color/scalable/places -r
cp ../symbolia/scalable/places ../symbolia-color/scalable/places -r
./all-folder-colors
echo "Done!"