#!/bin/bash

COLOR=#ffffff
sed -i -E 's/fill\="[^"]+"//g' *.svg
sed -i "s/<path/<path fill=\"$COLOR\"/g" *.svg
sed -i "s/<rect/<rect fill=\"$COLOR\"/g" *.svg
sed -i "s/<polygon/<polygon fill=\"$COLOR\"/g" *.svg
sed -i "s/<circle/<circle fill=\"$COLOR\"/g" *.svg
sed -i "s/<ellipse/<ellipse fill=\"$COLOR\"/g" *.svg
sed -i "s/<polyline/<polyline fill=\"$COLOR\"/g" *.svg
#sed -i -E "s/stroke\:[^\;]+/stroke\:$COLOR/g" *.svg
sed -i -E "s/fill\:\#[0-9]+/fill\:$COLOR/g" *.svg
