[Icon Theme]
Name=Symbolia Arc
Comment=Symbolic material icons.
Inherits=hicolor
Example=folder

# Directory list

Directories=scalable/actions,scalable/apps,scalable/categories,scalable/devices,scalable/emblems,scalable/mimetypes,scalable/places,scalable/status,scalable/actions@2x,scalable/apps@2x,scalable/categories@2x,scalable/devices@2x,scalable/emblems@2x,scalable/mimetypes@2x,scalable/places@2x,scalable/status@2x,symbolic/actions,symbolic/apps,symbolic/categories,symbolic/devices,symbolic/emblems,symbolic/mimetypes,symbolic/places,symbolic/status,symbolic/actions@2x,symbolic/apps@2x,symbolic/categories@2x,symbolic/devices@2x,symbolic/emblems@2x,symbolic/mimetypes@2x,symbolic/places@2x,symbolic/status@2x


# Actions

[scalable/actions]
Context=Actions
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[scalable/actions]
Context=Actions
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Applications

[scalable/apps]
Context=Applications
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[scalable/apps]
Context=Applications
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Categories

[scalable/categories]
Context=Categories
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[scalable/categories]
Context=Categories
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Devices

[scalable/devices]
Context=Devices
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[scalable/devices]
Scale=2
Context=Devices
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Emblems

[scalable/emblems]
Context=Emblems
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[scalable/emblems]
Context=Emblems
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Emotes

[scalable/emotes]
Context=Emotes
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[scalable/emotes]
Context=Emotes
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# MimeTypes

[scalable/mimetypes]
Context=Mimetypes
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[scalable/mimetypes]
Context=Mimetypes
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Places

[scalable/places]
Context=Places
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[scalable/places]
Context=Places
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Status

[scalable/status]
Context=Status
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[scalable/status]
Context=Status
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Actions

[symbolic/actions]
Context=Actions
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[symbolic/actions]
Context=Actions
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Applications

[symbolic/apps]
Context=Applications
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[symbolic/apps]
Context=Applications
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Categories

[symbolic/categories]
Context=Categories
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[symbolic/categories]
Context=Categories
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Devices

[symbolic/devices]
Context=Devices
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[symbolic/devices]
Scale=2
Context=Devices
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Emblems

[symbolic/emblems]
Context=Emblems
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[symbolic/emblems]
Context=Emblems
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Emotes

[symbolic/emotes]
Context=Emotes
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[symbolic/emotes]
Context=Emotes
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# MimeTypes

[symbolic/mimetypes]
Context=Mimetypes
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[symbolic/mimetypes]
Context=Mimetypes
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Places

[symbolic/places]
Context=Places
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[symbolic/places]
Context=Places
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable


# Status

[symbolic/status]
Context=Status
Size=16
MinSize=16
MaxSize=256
Type=Scalable

[symbolic/status]
Context=Status
Scale=2
Size=16
MinSize=16
MaxSize=256
Type=Scalable
